### ISSUE TITLE
Node.js上でもブラウザ上でも動くようにする

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey.js#11]
ブラウザにしかないAPI(e.g. fetch)などを良い感じにやる必要がある

**Comment by marihachi** [comment]
Conditional Exportsって機能で読み込みファイルを分岐できるらしい
webpackではブラウザ向けスクリプト、nodeではnode向けスクリプト、みたいにできるらしい

**Comment by marihachi** [comment]
参考になりそうな記事があった
https://endaaman.me/-/558ba96547319530593f5da2

**Comment by syuilo** [comment]
ふぅ〜む

**Comment by marihachi** [comment]
バンドル時の依存性解決を回避すればいい感じがする

**Comment by marihachi** [comment]
reconnecting-websocketはオプションからWebSocket likeなオブジェクトを受け取れるようにしてるね
オプションが指定されない場合はグローバルからWebSocketオブジェクトの取得を試みるみたい

**Comment by syuilo** [comment]
あーそれ良さそう

**Comment by marihachi** [comment]
モジュールを交換できるし良いかもね

**Comment by syuilo** [comment]
これやったらリリースするか

**Comment by marihachi** [comment]
これ解決してそう
