### ISSUE TITLE
ストリームのConnectionクラスをTS型定義用に公開してほしい

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/misskey.js#38]
Connectionクラスが公開されていないので、useChannelの結果を格納する変数の型を定義できない

**Comment by syuilo** [comment]
ReturnTypeじゃダメかしら

**Comment by tamaina** [comment]
ジェネリクスをうまく表現できないので挫折した

**Comment by syuilo** [comment]
https://stackoverflow.com/questions/50321419/typescript-returntype-of-generic-function
なるほど面倒そう

**Comment by tamaina** [comment]
🙏
